linters-settings:
  gocyclo:
    min-complexity: 50
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  revive:
    confidence: 0.8
  lll:
    line-length: 160
    # tab width in spaces. Default to 1.
    tab-width: 1
  funlen:
    lines: 150
    statements: 80

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - funlen
    - goconst
    - gocyclo
    - lll
    - misspell
    - revive

  # don't enable:
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - maligned
  # - prealloc

run:
  go: "1.24"
  skip-dirs:
    # - test/testdata_etc

issues:
  exclude-files:
    - ".*_test\\.go$"
  exclude-rules:
  #
